### ISSUE TITLE
How to register initial user account on local development environment?

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#48]
When creating a development environment, what is the recommended way to create an initial user?

I have tried the `python manage.py createsuperuser` command, but get a 500 error when trying to log in with the new user. The console log shows this:

```py
Internal Server Error: /
Traceback (most recent call last):
  File "/home/brylie/anaconda3/envs/CiviWiki-2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/brylie/code/CiviWiki/CiviWiki/frontend_views/views.py", line 20, in base_view
    a = Account.objects.get(user=request.user)
  File "/home/brylie/anaconda3/envs/CiviWiki-2.7/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/brylie/anaconda3/envs/CiviWiki-2.7/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Account matching query does not exist.
```

**Comment by JOO33** [comment]
A post signal handler for a new user save needs to be implemented within the account model so this doesn't happen. The usual route was to use the client sign-up page that routes to the auth/register which has the code to add a new account with the new user. For now, you will have to manually navigate to your db with a db client and manipulate your database.

**Comment by CiviWiki** [comment]
Do we need to add info on this to the readme?

**Comment by brylie** [comment]
Yes, any critical steps should be documented for developers/admins.
